### PR TITLE
fix: duplicate queries.json file generation

### LINKED ISSUE #145: Duplicate file
When following the installation procedure as suggested in the README (npm installation), and after executing
 `comunica-web-client-generator`, the `queries.json` file gets generated twice: 
 
 One in the folder where generator got executed and one in the `build` folder.

### PR DESCRIPTION
**Pull request by MaximStockmans**
Closes #145 

# Problem
The `queries.json` file was generated twice, once in the current working directory and once in the build directory. The file was first generated in the current working directory, and then passed to webpack for bundling. This bundling copied the file to the build directory, causing the file to exist twice. 

# Solution
Removed the `queries.json` file from the entries in the webpack plugin and instead wrote a custom plugin that moves this file into the build folder when webpack is triggered.

### CODE REVIEW

File: bin/generate.js [hunk 1]
```diff
@@ -60,6 +60,9 @@ if (args.h || args.help || args._.length > 1) {
     // Override the baseURL in the webpack config
     webpackConfig.baseURL.replace = baseURL;
 
+    // Override the buildContext in the webpack config
+    webpackConfig.buildContext.dir = destinationPath;
```
Comment (rubensworks) [inline bin/generate.js:64]: While I certainly like the effort you did you create a custom Webpack plugin, I wonder if it would not be sufficient to just configure a different `outputFile` when calling `compileSettings`? https://github.com/comunica/jQuery-Widget.js/blob/f72df7e8090bce15e2fae6c6a76f032ff55d2674/bin/generate.js#L52
Unless you see a good reason not to do this?

Comment (MaximStockmans) [reply bin/generate.js:64]: I considered using a different `outputFile` when calling `compileSettings`, as you suggested. However, I opted for the custom Webpack plugin to ensure that we do not depend on pre-existing files in the chosen build directory. As Webpack should ideally clean this chosen build directory first before creating the new build to avoid conflicts with older build files. 

The custom plugin approach would allow this cleaning to happen within Webpack, so all logic related to creating and populating the build folder remains consistent.

Comment (rubensworks) [reply bin/generate.js:64]: Ok, that's a very good point indeed!

**Comment by rubensworks** [comment]
Thanks @MaximStockmans!
Feel free to claim the bounty via https://opencollective.com/comunica-association ! (you can add VAT if needed)
